<a href="https://colab.research.google.com/github/nimitraheja/nimitraheja/blob/main/Feature_Construction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import  cross_val_score
from sklearn.linear_model import LogisticRegression

In [6]:
df=pd.read_csv('/content/train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [7]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [8]:
df.dropna(inplace=True)

In [9]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [10]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [12]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

Applying feature Construction

In [13]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [14]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [15]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2
myfunc(4)

1

In [16]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [17]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [18]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [19]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.7003174603174602)